Add check-*version targets to Mk/Makefile

diff --git a/Mk/Makefile b/Mk/Makefile
--- a/Mk/Makefile
+++ b/Mk/Makefile
@@ -43,3 +43,28 @@ site_perl.json: .PHONY
 		my %modules = map { $$_ => $$installed->version($$_) } $$installed->modules(); \
 		print JSON->new->canonical->encode(\%modules); \
 	' | ${JQ_CMD} . > ${.TARGET}
+
+check-version: .PHONY
+	find /usr/ports -mindepth 2 -maxdepth 2 -type d -name 'p5-*' | while read -r dir; do \
+		local_version="$$(make -C $${dir} -V PORTVERSION)"; \
+		cpan_name="$$(echo $${dir} | sed -r -e 's|.*/p5-||' -e s/-/::/g)"; \
+		cpan_version="$$(fetch --quiet --output=- https://fastapi.metacpan.org/v1/module/$${cpan_name} 2>/dev/null | ${JQ_CMD} .version)"; \
+		test -n "$${cpan_version}" || !	echo "$${dir##/usr/ports/} - $${cpan_name}: cannot get reply from cpan" || continue; \
+		cpan_version="$${cpan_version#v}"; \
+		test "$${local_version}" = "$${cpan_version}" && continue; \
+		echo "$${dir##/usr/ports/} $${local_version} - $${cpan_name} $${cpan_version}"; \
+	done
+
+check-version-installed: .PHONY
+	pkg query --evaluate '%n ~ p5-*' %o | while read -r origin; do \
+		dir="/usr/ports/$${origin}"; \
+		local_version="$$(make -C $${dir} -V PORTVERSION)"; \
+		cpan_name="$$(echo $${origin} | sed -r -e 's|.*/p5-||' -e s/-/::/g)"; \
+		test "$${origin}" = devel/p5-Locale-libintl && cpan_name=Locale::gettext_xs; \
+		test "$${origin}" = www/p5-libwww && cpan_name=LWP; \
+		cpan_version="$$(fetch --quiet --output=- https://fastapi.metacpan.org/v1/module/$${cpan_name} 2>/dev/null | ${JQ_CMD} .version)"; \
+		test -n "$${cpan_version}" || !	echo "$${origin} ${local_version} - $${cpan_name}: cannot get reply from cpan" || continue; \
+		cpan_version="$${cpan_version#v}"; \
+		test "echo $${local_version}==$${cpan_version} | bc" = 0 || continue; \
+		echo "$${origin} $${local_version} - $${cpan_name} $${cpan_version}"; \
+	done
